name: Build and Push to GHCR

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/queone/cntimage:latest .

      - name: Push the Docker image
        run: |
          docker push ghcr.io/queone/cntimage:latest

      - name: Delete old images from GHCR (ubi9:*)
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          REPO="queone/ubi9"

          # Get all image versions
          IMAGES=$(curl -s -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/users/queone/packages/container/${REPO}/versions" | jq -r '.[].id')

          # Delete each image version
          for IMAGE_ID in $IMAGES; do
            echo "Deleting image ID: $IMAGE_ID"
            curl -X DELETE -H "Authorization: Bearer $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/users/queone/packages/container/${REPO}/versions/$IMAGE_ID"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
