name: Build and Release Image

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: "Select the Dockerfile to use"
        required: true
        type: choice
        options:
          - Dockerfile.base
          - Dockerfile.vault

permissions:
  contents: read  # Needed because this is still a Private repo
  packages: write # Needed to push images to GitHub Container Registry 

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Ensure we fetch all branches

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image name and version from Dockerfile
        run: |
          read IMAGE_NAME IMAGE_VERSION < <(.github/scripts/get-name-and-version.sh ${{ github.event.inputs.dockerfile }})
          echo "Extracted image name: $IMAGE_NAME, version: $IMAGE_VERSION"  # Debugging log
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV

      - name: DEBUG - image name and version
        run: |
          echo "IMAGE_NAME: '${{ env.IMAGE_NAME }}'"
          echo "IMAGE_VERSION: '${{ env.IMAGE_VERSION }}'"

      - name: Build the image with auto-generated metadata
        run: |
          SOURCE_REPO="https://github.com/${{ github.repository }}"
          CREATED_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          echo "Building image: ghcr.io/queone/${IMAGE_NAME}:${IMAGE_VERSION}"  # Debugging log

          docker build -f ${{ github.event.inputs.dockerfile }} \
            --label "org.opencontainers.image.source=${SOURCE_REPO}" \
            --label "org.opencontainers.image.created=${CREATED_DATE}" \
            -t ghcr.io/queone/${IMAGE_NAME}:${IMAGE_VERSION} \
            -t ghcr.io/queone/${IMAGE_NAME}:latest .

      - name: Push the images to the registry
        run: |
          docker push ghcr.io/queone/${IMAGE_NAME}:${IMAGE_VERSION}
          docker push ghcr.io/queone/${IMAGE_NAME}:latest

      - name: Verify pushed images in GHCR
        run: |
          echo "Checking images in GitHub Container Registry..."

          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          IMAGE_REPO="ghcr.io/queone/${IMAGE_NAME}"

          echo "Fetching image tags for: $IMAGE_REPO"

          RESPONSE=$(curl -s -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/orgs/queone/packages/container/${IMAGE_NAME}/versions")

          echo "GHCR API Response:"
          echo "$RESPONSE" | jq -r '.[] | {id: .id, created: .created_at, tags: .metadata.container.tags}'
