name: Manually Test Latest Image

on:
  workflow_dispatch:

jobs:
  test-image:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all tags are fetched
          ref: main

      - name: Get latest tag
        id: versioning
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
          
          if [[ -z "$LATEST_TAG" ]]; then
            echo "No tags found, using default 1.0.0"
            LATEST_TAG="1.0.0"
          fi
          
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Using tag: $LATEST_TAG"

  test-container:
    runs-on: ubuntu-latest
    needs: test-image
    container:
      image: ghcr.io/queone/cntimage:${{ env.LATEST_TAG }}

    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Test commands
        run: |
          Gre='\e[1;32m' Red='\e[1;31m' Pur='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
          printf "${Gre}START${Rst}\n"
          git --version
          ls -l
          cat /etc/os-release
          uname -m
          go version
          vault version
          printf "${Red}END!${Rst}\n"
