name: Remove Image

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: "Select the Dockerfile to use"
        required: true
        type: choice
        options:
          - Dockerfile.base
          - Dockerfile.vault
          - Dockerfile.cntimage
      version:
        description: "Specify the version to remove (e.g., 1.0.0)"
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  remove_image:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Ensure we fetch all tags

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image name from Dockerfile
        id: extract
        run: |
          # Read the Dockerfile and extract the image name
          RAW_IMAGE_NAME=$(grep -E '^LABEL name=' ${{ github.event.inputs.dockerfile }})
          echo "Raw image name: '$RAW_IMAGE_NAME'"
          IMAGE_NAME=$(echo "$RAW_IMAGE_NAME" | cut -d'=' -f2 | tr -d ' "')
          IMAGE_NAME=$(echo "$IMAGE_NAME" | sed 's/\\$//')  # Remove trailing backslash if present
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Debugging output
        run: |
          echo "IMAGE_NAME: '${{ env.IMAGE_NAME }}'"
          echo "VERSION: '${{ github.event.inputs.version }}'"

      - name: Remove previously released image and package
        run: .github/scripts/remove-image.sh "${{ env.IMAGE_NAME }}" "${{ github.event.inputs.version }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
