name: Remove Image

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: "Select the Dockerfile to use"
        required: true
        type: choice
        options:
          - Dockerfile.base
          - Dockerfile.vault
      version:
        description: "Specify the version to remove (e.g., 1.0.0)"
        required: true
        type: string

permissions:
  packages: write # Needed to delete images from GitHub Container Registry

jobs:
  remove_image:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image name from Dockerfile
        id: extract
        run: |
          read IMAGE_NAME _ < <(.github/scripts/get-name-and-version.sh ${{ github.event.inputs.dockerfile }})
          echo "Extracted image name: $IMAGE_NAME"  # Debugging log
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Debugging output
        run: |
          echo "IMAGE_NAME: '${{ env.IMAGE_NAME }}'"
          echo "VERSION (from input): '${{ github.event.inputs.version }}'"

      - name: Remove previously released image and package
        run: .github/scripts/remove-image.sh "${{ env.IMAGE_NAME }}" "${{ github.event.inputs.version }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
