name: Remove Image

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: "Select the Dockerfile to use"
        required: true
        type: choice
        options:
          - Dockerfile.base
          - Dockerfile.vault
      image_tag:
        description: "Specify the tag to remove (e.g., 1.0.0)"
        required: true
        type: string

permissions:
  contents: read  # Required to checkout private repo
  packages: write # Required to delete images from GitHub Container Registry

jobs:
  remove_image:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we fetch all branches

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image name from Dockerfile
        run: |
          Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
          read IMAGE_NAME _ < <(.github/scripts/get-name-and-tag.sh ${{ github.event.inputs.dockerfile }})
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          # DEBUG OUTPUT
          printf "==> IMAGE_NAME: ${Blu}${{ env.IMAGE_NAME }}${Rst}\n"
          printf "==> IMAGE_TAG : ${Blu}${{ github.event.inputs.image_tag }}${Rst}\n"

      - name: Remove image and package
        run: .github/scripts/remove-image.sh "${{ env.IMAGE_NAME }}" "${{ github.event.inputs.image_tag }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
